package masterclass

// MasterclassDefinition contains the entire structure of the masterclass
var MasterclassDefinition = []Module{
	{
		ID:          "welcome",
		Slug:        "welcome",
		Title:       "Welcome",
		Description: "Get started with your habit transformation journey",
		Emoji:       "👋",
		Order:       0,
		Lessons: []Lesson{
			{
				ID:          "getting-started",
				Slug:        "getting-started",
				Title:       "Getting Started",
				Emoji:       "🚀",
				Type:        LessonTypeText,
				ModuleSlug:  "welcome",
				Order:       1,
				Description: "Learn how to make the most of this masterclass",
			},
			{
				ID:          "course-overview",
				Slug:        "course-overview",
				Title:       "Course Overview",
				Emoji:       "🗺️",
				Type:        LessonTypeVideo,
				ModuleSlug:  "welcome",
				Order:       2,
				Description: "Preview what you'll learn in this masterclass",
			},
		},
	},
	{
		ID:          "introduction",
		Slug:        "introduction",
		Title:       "Introduction to Habits",
		Description: "Learn the fundamentals of habit formation and why habits are so powerful",
		Emoji:       "🚀",
		Order:       1,
		Category:    "Masterclass",
		Lessons: []Lesson{
			{
				ID:          "why-habits-matter",
				Slug:        "why-habits-matter",
				Title:       "Why Habits Matter",
				Emoji:       "💡",
				Type:        LessonTypeText,
				ModuleSlug:  "introduction",
				Order:       1,
				Description: "Understand the importance of habits in shaping your identity",
			},
			{
				ID:          "science-of-habit-formation",
				Slug:        "science-of-habit-formation",
				Title:       "The Science of Habits",
				Emoji:       "🧪",
				Type:        LessonTypeVideo,
				ModuleSlug:  "introduction",
				Order:       2,
				Description: "Discover the neurological basis of habit formation",
			},
			{
				ID:          "setting-your-intention",
				Slug:        "setting-your-intention",
				Title:       "Setting Your Intention",
				Emoji:       "🎯",
				Type:        LessonTypeText,
				ModuleSlug:  "introduction",
				Order:       3,
				Description: "Learn how to set clear intentions for your habit journey",
			},
		},
	},
	{
		ID:          "foundations",
		Slug:        "foundations",
		Title:       "Habit Foundations",
		Description: "Master the core principles behind effective habit building",
		Emoji:       "🏗️",
		Order:       2,
		Category:    "Masterclass",
		Lessons: []Lesson{
			{
				ID:          "four-laws",
				Slug:        "four-laws",
				Title:       "The Four Laws of Behavior Change",
				Emoji:       "📜",
				Type:        LessonTypeVideo,
				ModuleSlug:  "foundations",
				Order:       1,
				Description: "Explore the four fundamental laws that govern habit formation",
			},
			{
				ID:          "identity-based-habits",
				Slug:        "identity-based-habits",
				Title:       "Identity-Based Habits",
				Emoji:       "🔄",
				Type:        LessonTypeText,
				ModuleSlug:  "foundations",
				Order:       2,
				Description: "Learn how to align your habits with your identity",
			},
			{
				ID:          "habit-stacking",
				Slug:        "habit-stacking",
				Title:       "Habit Stacking",
				Emoji:       "📚",
				Type:        LessonTypeVideo,
				ModuleSlug:  "foundations",
				Order:       3,
				Description: "Discover techniques to build new habits on top of existing ones",
			},
		},
	},
	{
		ID:          "systems",
		Slug:        "systems",
		Title:       "Building Systems",
		Description: "Create effective systems to support your habit goals",
		Emoji:       "⚙️",
		Order:       3,
		Category:    "Masterclass",
		Lessons: []Lesson{
			{
				ID:          "environment-design",
				Slug:        "environment-design",
				Title:       "Environment Design",
				Emoji:       "🏠",
				Type:        LessonTypeVideo,
				ModuleSlug:  "systems",
				Order:       1,
				Description: "Learn how to optimize your environment for habit success",
			},
			{
				ID:          "implementation-intentions",
				Slug:        "implementation-intentions",
				Title:       "Implementation Intentions",
				Emoji:       "📝",
				Type:        LessonTypeText,
				ModuleSlug:  "systems",
				Order:       2,
				Description: "Master the if-then planning method for habits",
			},
			{
				ID:          "habit-tracking",
				Slug:        "habit-tracking",
				Title:       "Habit Tracking Methods",
				Emoji:       "📊",
				Type:        LessonTypeVideo,
				ModuleSlug:  "systems",
				Order:       3,
				Description: "Explore different approaches to tracking your habits",
			},
		},
	},
	{
		ID:          "productivity",
		Slug:        "productivity",
		Title:       "Productivity Mastery",
		Description: "Optimize your output while maintaining balance and focus",
		Emoji:       "📈",
		Order:       4,
		Category:    "Challenges",
		Lessons: []Lesson{
			{
				ID:          "defining-productivity",
				Slug:        "defining-productivity",
				Title:       "What is Productivity?",
				Emoji:       "🧠",
				Type:        LessonTypeText,
				ModuleSlug:  "productivity",
				Order:       1,
				Description: "Redefining productivity beyond mere busyness",
			},
			{
				ID:          "goal-behind-goal",
				Slug:        "goal-behind-goal",
				Title:       "The Goal Behind the Goal",
				Emoji:       "🎯",
				Type:        LessonTypeVideo,
				ModuleSlug:  "productivity",
				Order:       2,
				Description: "Uncovering the true purpose of your objectives",
			},
			{
				ID:          "power-of-constraints",
				Slug:        "power-of-constraints",
				Title:       "The Point of Constraint",
				Emoji:       "🔒",
				Type:        LessonTypeText,
				ModuleSlug:  "productivity",
				Order:       3,
				Description: "Leveraging limitations for focused execution",
			},
			{
				ID:          "self-management",
				Slug:        "self-management",
				Title:       "Managing Yourself",
				Emoji:       "🧘",
				Type:        LessonTypeVideo,
				ModuleSlug:  "productivity",
				Order:       4,
				Description: "Personal governance systems for sustained performance",
			},
			{
				ID:          "time-mastery",
				Slug:        "time-mastery",
				Title:       "Time Block Mastery",
				Emoji:       "🍅",
				Type:        LessonTypeVideo,
				ModuleSlug:  "productivity",
				Order:       5,
				Description: "Advanced techniques for intentional scheduling",
			},
			{
				ID:          "priority-frameworks",
				Slug:        "priority-frameworks",
				Title:       "Priority Frameworks",
				Emoji:       "📌",
				Type:        LessonTypeText,
				ModuleSlug:  "productivity",
				Order:       6,
				Description: "Systems for effective decision filtering",
			},
			{
				ID:          "energy-management",
				Slug:        "energy-management",
				Title:       "Energy Management",
				Emoji:       "⚡",
				Type:        LessonTypeVideo,
				ModuleSlug:  "productivity",
				Order:       7,
				Description: "Optimizing physical/mental resources for output",
			},
			{
				ID:          "automation-leverage",
				Slug:        "automation-leverage",
				Title:       "Automation & Leverage",
				Emoji:       "🤖",
				Type:        LessonTypeText,
				ModuleSlug:  "productivity",
				Order:       8,
				Description: "Building systems that work when you're not",
			},
		},
	},
	// Additional modules follow the same pattern...
}
