package masterclass

// MasterclassDefinition contains the entire structure of the masterclass
var MasterclassDefinition = []Module{
	{
		ID:          "introduction",
		Slug:        "introduction",
		Title:       "Introduction to Habits",
		Description: "Learn the fundamentals of habit formation and why habits are so powerful",
		Emoji:       "🚀",
		Order:       1,
		Lessons: []Lesson{
			{
				ID:          "why-habits-matter",
				Slug:        "why-habits-matter",
				Title:       "Why Habits Matter",
				Emoji:       "💡",
				Type:        LessonTypeText,
				ModuleSlug:  "introduction",
				Order:       1,
				Description: "Understand the importance of habits in shaping your identity",
			},
			{
				ID:          "science-of-habit-formation",
				Slug:        "science-of-habit-formation",
				Title:       "The Science of Habit Formation",
				Emoji:       "🧪",
				Type:        LessonTypeVideo,
				ModuleSlug:  "introduction",
				Order:       2,
				Description: "Discover the neurological basis of habit formation",
			},
			{
				ID:          "setting-your-intention",
				Slug:        "setting-your-intention",
				Title:       "Setting Your Intention",
				Emoji:       "🎯",
				Type:        LessonTypeText,
				ModuleSlug:  "introduction",
				Order:       3,
				Description: "Learn how to set clear intentions for your habit journey",
			},
		},
	},
	{
		ID:          "foundations",
		Slug:        "foundations",
		Title:       "Habit Foundations",
		Description: "Master the core principles behind effective habit building",
		Emoji:       "🏗️",
		Order:       2,
		Lessons: []Lesson{
			{
				ID:          "four-laws",
				Slug:        "four-laws",
				Title:       "The Four Laws of Behavior Change",
				Emoji:       "📜",
				Type:        LessonTypeVideo,
				ModuleSlug:  "foundations",
				Order:       1,
				Description: "Explore the four fundamental laws that govern habit formation",
			},
			{
				ID:          "identity-based-habits",
				Slug:        "identity-based-habits",
				Title:       "Identity-Based Habits",
				Emoji:       "🔄",
				Type:        LessonTypeText,
				ModuleSlug:  "foundations",
				Order:       2,
				Description: "Learn how to align your habits with your identity",
			},
			{
				ID:          "habit-stacking",
				Slug:        "habit-stacking",
				Title:       "Habit Stacking",
				Emoji:       "📚",
				Type:        LessonTypeVideo,
				ModuleSlug:  "foundations",
				Order:       3,
				Description: "Discover techniques to build new habits on top of existing ones",
			},
		},
	},
	{
		ID:          "systems",
		Slug:        "systems",
		Title:       "Building Systems",
		Description: "Create effective systems to support your habit goals",
		Emoji:       "⚙️",
		Order:       3,
		Lessons: []Lesson{
			{
				ID:          "environment-design",
				Slug:        "environment-design",
				Title:       "Environment Design",
				Emoji:       "🏠",
				Type:        LessonTypeVideo,
				ModuleSlug:  "systems",
				Order:       1,
				Description: "Learn how to optimize your environment for habit success",
			},
			{
				ID:          "implementation-intentions",
				Slug:        "implementation-intentions",
				Title:       "Implementation Intentions",
				Emoji:       "📝",
				Type:        LessonTypeText,
				ModuleSlug:  "systems",
				Order:       2,
				Description: "Master the if-then planning method for habits",
			},
			{
				ID:          "habit-tracking",
				Slug:        "habit-tracking",
				Title:       "Habit Tracking Methods",
				Emoji:       "📊",
				Type:        LessonTypeVideo,
				ModuleSlug:  "systems",
				Order:       3,
				Description: "Explore different approaches to tracking your habits",
			},
		},
	},
	// Additional modules follow the same pattern...
}
